const HDWalletProvider = require('truffle-hdwallet-provider');
const Web3 = require('web3');
const {interface, bytecode} = require('./compile');

const provider = new HDWalletProvider(
    '***MNUMONIC WOULD GO HERE*****',
    'https://rinkeby.infura.io/****NODEKEYHERE*****'
);
const web3 = new Web3(provider);

//url: https://rinkeby.infura.io/****NODEKEYHERE*****

const deploy = async () => {
    //gather a list of all the accounts generated by my mnuenomic on the rinkeby network
    const accounts = await web3.eth.getAccounts();
    console.log('attempting to deploy with account: ', accounts[0]);

    //deploy the contract with one of those accounts
    const inbox = await new web3.eth.Contract(JSON.parse(interface))
                .deploy({data:'0x'+bytecode, arguments:['Hi there!']})
                .send({from: accounts[0], gas: '1000000'});

    console.log("Contract deployed to: ", inbox.options.address);
};

deploy();